
'use client'
// import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryClientProvider client={queryClient}>
      <html lang="en">
        <body className="bg-gray-100 text-gray-800">
          <header className="bg-white shadow">
            <nav className="container mx-auto flex justify-between items-center p-4">
              <h1 className="text-xl font-bold">
                <Link href="/" className="text-blue-500 hover:text-blue-700">
                  MyApp
                </Link>
              </h1>
              <div className="space-x-4">
                <Link href="/" className="text-gray-600 hover:text-blue-500">
                  Home
                </Link>
                <Link href="/login" className="text-gray-600 hover:text-blue-500">
                  Login
                </Link>
                <Link href="/signup" className="text-gray-600 hover:text-blue-500">
                  Sign Up
                </Link>
              </div>
            </nav>
          </header>
          <main className="container mx-auto mt-8 p-4">{children}</main>
        </body>
      </html>
    </QueryClientProvider>
  );
}
