import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

import React from "react";

/*
  root layout 컴포넌트
 */

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header style={{height:"200px" , borderColor:"black", border:"solid"}}>
          헤더입니다<br />
          <ul>
            <li>
              <Link href={"/"}>index</Link>
            </li>
            <li>
              <Link href={"/item/1"}>item</Link>
            </li>
            <li>
              <Link href={"/search?q=서은"}>Search</Link>
            </li>
            <li>
              <Link href={"/users/login"}>login</Link>
            </li>
            <li>
              <Link href={"/users/signup"}>signup</Link>
            </li>
            <li>
              <Link href={"/assignment"}>Assignment Page</Link>
            </li>
          </ul>
        </header>
        <main style={{ border:"solid"}}>
          {children}
        </main>
        <footer style={{height:"100px",border:"solid"}}>
          푸터 입니다
        </footer>
      </body>
    </html>
  );
}
