import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

import React from "react";
import Image from "next/image";
import GloabalLoading from "@/component/GloabalLoading";

/*
  root layout 컴포넌트
 */

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
          <Link href={"/"}>
              <Image
                src="/navbar-brand.svg"
                alt="Logo"
                width={143}
                height={40}
                className="logo" />
          </Link>
          <ul>
            <li>
              <Link href={"/iga"}>캠페인별 수익 내용</Link>
            </li>
            <li>
              <Link href={"/iga2"}>월별 성과</Link>
            </li>
            <li>
              <Link href={"/iga3"}>캠페인 ROI 분석</Link>
            </li>
          </ul>
        </header>
        <main>
          <GloabalLoading />
          {children}
        </main>
        <footer className="footer st-current">
          <div className="footer__copyright">
            <div className="container">
              <div className="container__inner">
                <div className="address information-section" style={{ marginLeft: "0.0rem", cursor: "pointer" }} >개인정보처리방침</div>
                <div className="address" style={{ marginLeft: "0.0rem", cursor: "pointer" }} >저작권정책</div>
                <div className="address">서울특별시 용산구 서빙고로 17, 24층, 25층, 26층 (한강로3가, 센트럴파크타워)</div>
                <div className="copyright">© 2019. IGAWorks Inc. All rights reserved.</div>
              </div>
            </div>
            <br />
            <div className="container">
              <div className="container__inner">
                <div className="logo">
                  <Image
                    src="/igaw-gray.svg"
                    alt="Logo"
                    width={79}
                    height={22}
                    className="logo" />
                </div>
              </div>
            </div>
            <br />
          </div>
        </footer>
      </body>
    </html>
  );
}
